### PR TITLE
Bring hotfixes from release/public-v1 back to master (CCPP changes)

### PR DESCRIPTION
**Pull request by climbfuji**
Updates for CCPP suites, `.gitmodules` and submodule pointers for ccpp-framework and ccpp-physics. These submodule pointers may need to be updated again if changes are made to the branches bugfixes_from_public_release in @climbfuji's forks of ccpp-framework and ccpp-physics.

### CODE REVIEW

**Comment by climbfuji** [comment]
Draft PRs for ccpp-framework and ccpp-physics are here:

https://github.com/NCAR/ccpp-framework/pull/289
https://github.com/NCAR/ccpp-physics/pull/448

**Comment by climbfuji** [comment]
@DusanJovic-NOAA I noticed that the updates to the dycore are still missing in your bugfixes_from_public_release branch of fv3atm. Also, several updates for ufs-weather-model (cmake config files jet -> jet.intel, stampede.intel, ...) and more are missing.

**Comment by DusanJovic-NOAA** [comment]
@climbfuji Should I merge this PR to my branch? Do these changes require new baselines?

**Comment by climbfuji** [comment]
Yes, please merge them. These changes do not require a new baseline. Thanks!

**Pull request merged**
